export const BODY_PARTS: string[] = [
  'Tête',
  'Cou',
  'Cervicales',
  'Bras droit',
  'Bras gauche',
  'Main droite',
  'Main gauche',
  'Doigts droit',
  'Doigts gauche',
  'Torse',
  'Bassin',
  'Jambe droite',
  'Jambe gauche',
  'Pied droit',
  'Pied gauche',
]
